package kr.decacross.daemon.install

import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.attribute.PosixFilePermission
import java.time.Instant

/**
 * server.properties / 실행 스크립트 / eula.txt 생성 (기획서 §4.4, §4.5).
 *
 * # 불변식
 * - 스크립트는 런처 없이도 실행된다 (불변식 11). 런처 경로·환경변수에 의존하지 않는다.
 * - Java 는 절대경로로 호출한다. JAVA_HOME/PATH 를 건드리지 않는다 (불변식 10).
 * - EULA 는 사용자가 명시적으로 동의했을 때만 `eula=true` 를 쓴다.
 */
object Config {
    /** Aikar 플래그 (docs.papermc.io/paper/aikars-flags). 12G 기준 분기. JDK 25 에서 전부 유효함을 확인(2026-09-17). */
    fun aikarFlags(ramMb: Int): List<String> {
        val big = ramMb >= 12 * 1024
        return listOf(
            "-XX:+UseG1GC",
            "-XX:+ParallelRefProcEnabled",
            "-XX:MaxGCPauseMillis=200",
            "-XX:+UnlockExperimentalVMOptions",
            "-XX:+DisableExplicitGC",
            "-XX:+AlwaysPreTouch",
            "-XX:G1NewSizePercent=${if (big) 40 else 30}",
            "-XX:G1MaxNewSizePercent=${if (big) 50 else 40}",
            "-XX:G1HeapRegionSize=${if (big) "16M" else "8M"}",
            "-XX:G1ReservePercent=${if (big) 15 else 20}",
            "-XX:G1HeapWastePercent=5",
            "-XX:G1MixedGCCountTarget=4",
            "-XX:InitiatingHeapOccupancyPercent=${if (big) 20 else 15}",
            "-XX:G1MixedGCLiveThresholdPercent=90",
            "-XX:G1RSetUpdatingPauseTimePercent=5",
            "-XX:SurvivorRatio=32",
            "-XX:+PerfDisableSharedMem",
            "-XX:MaxTenuringThreshold=1",
            "-Dusing.aikars.flags=https://mcflags.emc.gs",
            "-Daikars.new.flags=true",
        )
    }

    /** 서버 JVM 인자 전체 (Xms/Xmx + Aikar + 인코딩). 스크립트와 Supervisor 가 같은 목록을 쓴다. */
    fun jvmArgs(ramMb: Int): List<String> =
        listOf("-Xms${ramMb}M", "-Xmx${ramMb}M") + aikarFlags(ramMb) +
            listOf("-Dfile.encoding=UTF-8", "-Dstdout.encoding=UTF-8", "-Dstderr.encoding=UTF-8", "-Dterminal.jline=false")

    fun defaultProperties(spec: InstallSpec): Map<String, String> =
        linkedMapOf(
            "motd" to spec.displayName,
            "server-port" to spec.port.toString(),
            "max-players" to "20",
            "difficulty" to "normal",
            "online-mode" to "true", // 보안 기본값. 끄려면 사용자가 명시적으로.
            "view-distance" to "10",
            "simulation-distance" to "10",
            "enable-command-block" to "false",
            "spawn-protection" to "0",
        ) + spec.properties

    fun writeServerProperties(dir: Path, props: Map<String, String>) {
        val text = buildString {
            append("#Minecraft server properties\n")
            append("#Generated by DecaCross ").append(Instant.now()).append('\n')
            for ((k, v) in props) append(k).append('=').append(escapeProp(v)).append('\n')
        }
        Files.writeString(dir.resolve("server.properties"), text)
    }

    private fun escapeProp(v: String): String = v.replace("\\", "\\\\").replace("\n", "\\n")

    fun startBat(spec: InstallSpec, coreJar: String): String {
        val args = jvmArgs(spec.ramMb).joinToString(" ")
        return buildString {
            append("@echo off\r\n")
            append("chcp 65001 >nul\r\n")
            append("title DecaCross - ").append(spec.displayName).append("\r\n")
            append("cd /d \"%~dp0\"\r\n")
            append("\"").append(spec.javaExe.toAbsolutePath()).append("\" ").append(args)
            append(" -jar \"").append(coreJar).append("\" nogui\r\n")
            append("pause\r\n")
        }
    }

    fun startSh(spec: InstallSpec, coreJar: String): String {
        val args = jvmArgs(spec.ramMb).joinToString(" ")
        return buildString {
            append("#!/usr/bin/env bash\n")
            append("cd \"$(dirname \"$0\")\"\n")
            append("exec \"").append(spec.javaExe.toAbsolutePath()).append("\" ").append(args)
            append(" -jar \"").append(coreJar).append("\" nogui\n")
        }
    }

    /** 설치 후 Java/RAM 이 바뀌었을 때(06 fix 등) 스크립트만 다시 쓴다. */
    fun writeStartScripts(dir: Path, javaExe: String, ramMb: Int, coreJar: String, displayName: String) {
        val mc = kr.decacross.compat.model.McVersion(kr.decacross.compat.model.McOrdinal(0), "", kotlin.time.Instant.fromEpochSeconds(0), false, 0, 0, null, null)
        val core = kr.decacross.compat.model.CoreBuild(kr.decacross.compat.model.CoreKey.PAPER, mc.ordinal, "", kr.decacross.compat.model.Channel.STABLE, "", "", 0)
        val spec = InstallSpec(name = displayName, mc = mc, core = core, javaExe = Path.of(javaExe), ramMb = ramMb, acceptEula = true, displayName = displayName)
        writeStartScripts(dir, spec, coreJar)
    }

    fun writeStartScripts(dir: Path, spec: InstallSpec, coreJar: String) {
        Files.writeString(dir.resolve("start.bat"), startBat(spec, coreJar))
        val sh = dir.resolve("start.sh")
        Files.writeString(sh, startSh(spec, coreJar))
        runCatching {
            Files.setPosixFilePermissions(
                sh,
                setOf(
                    PosixFilePermission.OWNER_READ, PosixFilePermission.OWNER_WRITE, PosixFilePermission.OWNER_EXECUTE,
                    PosixFilePermission.GROUP_READ, PosixFilePermission.GROUP_EXECUTE,
                    PosixFilePermission.OTHERS_READ, PosixFilePermission.OTHERS_EXECUTE,
                ),
            )
        } // Windows 에서는 무시
    }

    /** `eula=true` 는 [accepted] 일 때만. 동의 시각을 주석으로 남긴다. */
    fun writeEula(dir: Path, accepted: Boolean, at: Instant = Instant.now()) {
        val text = buildString {
            append("#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).\n")
            if (accepted) append("#Accepted via DecaCross at ").append(at).append('\n')
            append("eula=").append(accepted).append('\n')
        }
        Files.writeString(dir.resolve("eula.txt"), text)
    }
}
